### ISSUE TITLE
matrix_float3x3 is not cross platform type

### ISSUE THREAD

**Issue by yangfengzzz** [SwiftGFX/SwiftMath#7]
as far as I know, matrix_float3x3 is from the SIMD framework(Part of Accelerator framework) but not the standard library of Swift

**Comment by s1ddok** [comment]
yes, that’s why we provide manual implementation under `NOSIMD` flag! https://github.com/SwiftGFX/SwiftMath/blob/master/Sources/Matrix3x3%2Bnosimd.swift
